### PR TITLE
Update PodDisruptionBudgets API version

### LINKED ISSUE #833: PodDisruptionBudget policies fail to create at k8s v1.25+
### Describe the issue you're reporting

The `splunk-otel-collector` - `pdb-cluster-receiver.yaml` and `pdb-gateway.yaml` policies are hardcoded to be `apiVersion: policy/v1beta1`. That causes creation of them to fail while trying to deploy to k8s clusters at version 1.25 and above - due to its earlier deprecation at 1.21 and now [removal at 1.25](https://kubernetes.io/docs/reference/using-api/deprecation-guide/#poddisruptionbudget-v125).
```
Error: unable to build kubernetes objects from current release manifest: unable to recognize "":
no matches for kind "PodDisruptionBudget" in version "policy/v1beta1"
```

We've found that an easy override is setting `PodDisruptionBudget: null` in `values.yaml` and creating the policies separately, but having that not be hardcoded would also be nice.
I'll be wanting to open a PR shortly with the non-hardcoded fix.

### PR DESCRIPTION
**Pull request by legoGoat**
Fixes #833 PodDisruptionBudget policies fail to create at k8s v1.25+

Description: `Capabilities.KubeVersion.Version` checks the kube version. If above 1.21, `apiVersion: policy/v1` is set for PodDisruptionBudget, else `apiVersion: policy/v1beta1`.

### CODE REVIEW

**Review by dmitryax — APPROVED** [review]
LGTM. Thank you, @legoGoat!

**Comment by legoGoat** [comment]
@dmitryax hi, sorry, any advice on the test that failed? It was the functional tests bit that failed and I wouldn't think this change would affect any changes... Could this be fixed just rerunning the workflow or is there something obvious I'm missing that's at fault?

**Comment by dmitryax** [comment]
That test is flaky, sorry

**Comment by legoGoat** [comment]
Not a problem, just got me worried there for a second 🙈 
Now if it succeeds this time around, should I dare to push an extra commit with a `CHANGELOG.md` change?

**Comment by dmitryax** [comment]
> Now if it succeeds this time around, should I dare to push an extra commit with a CHANGELOG.md change?

Sure, thank you!

**Comment by legoGoat** [comment]
oh no, functional tests strike again 😢 though it's cri-o this time, not docker

**Comment by atoulme** [comment]
rerunning.

**Pull request merged**
