### PR TITLE
add max_batch_size to recombine instructions

### PR DESCRIPTION
**Pull request by atoulme**
Sets values for max_batch_size (default is 1000) for crio to 8, containerd and docker to 16 respectively.

### CODE REVIEW

**Comment by matthewmodestino** [comment]
Suggest perhaps we go with `max_log_size` first to see if we can just set the size to 1MB vs the different settings for docker and cri-o/containerd. 


https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/pkg/stanza/docs/operators/recombine.md

If we do go with `max_batch_size` docker splits at 16384 and cri-o/containerd is 8192, so I would flip your numbers. 8 for docker, 16 for cri-o/containerd.

Lets be sure to capture the behaviour of 20MB+ logs, i assume we would flush then recombine the next batch from the big log together. Will help us identify them in Splunk.

**Comment by atoulme** [comment]
OK, I'll rework this.

**Review by jvoravong — APPROVED** [review]

**Comment by atoulme** [comment]
Let's go first with #713 as indicated by @matthewmodestino

**Comment by atoulme** [comment]
Closing in favor of #713.

**Pull request closed without merging**
