### PR TITLE
Add support for splunk-otel-java v2.x.x

### PR DESCRIPTION
**Pull request by jvoravong**
**Description:** <Describe what has changed.>
- Adopt Java 2.x in the collector and chart
- Update any failing tests as needed
- Publish any breaking changes notes as needed

### CODE REVIEW

**Comment by atoulme** [comment]
` --- FAIL: Test_Functions/java_traces_captured (181.00s)` as expected, this changes the format of the traces we expose quite a bit.

**Comment by atoulme** [comment]
Quick hunch, can you ignore the resource attribute `network.peer.port` ?

**Comment by aunshc** [comment]
Quick note once this is out of the draft state: we should add this to the changelog and reference that runtime metrics will now be enabled by default with Java 2.x by linking to this migration guide as well https://docs.splunk.com/observability/en/gdi/get-data-in/application/java/migrate-metrics.html.

**Comment by atoulme** [comment]
very close, please add one ignore for the resource attribute "telemetry.distro.version"

**Review by atoulme — APPROVED** [review]
LGTM, asking @breedx-splk to review, esp docs.

**Review by breedx-splk — APPROVED** [review]
Seems fine to me. I didn't cross-check the entire list of metric name and attribute changes, but it seems about right.

**Pull request merged**
