### PR TITLE
Rename parameter groups for Splunk OTel Collector components

### PR DESCRIPTION
**Pull request by dmitryax**
Rename the following parameter groups according to [Splunk GDI Specification](https://github.com/signalfx/gdi-specification/blob/main/specification/configuration.md#kubernetes-package-management-solutions):
- `otelAgent` -> `agent`
- `otelCollector` -> `gateway`
- `otelK8sClusterReceiver` -> `clusterReceiver`

### CODE REVIEW

**Comment by chaitanyaphalak** [comment]
I am guessing this change is for more clarity and reducing ambiguity?

**Comment by dmitryax** [comment]
Yes. Decision was made [here](https://github.com/signalfx/gdi-specification/pull/147) to establish this configuration interface for helm chart and operator prior to declaring GA

**Review by rockb1017 — APPROVED** [review]

**Comment by rockb1017** [comment]
let me see if i can push a commit to here

**Comment by rockb1017** [comment]
oh i can. please review @dmitryax

**Comment by dmitryax** [comment]
Awesome! Thanks @rockb1017!

**Pull request merged**
