### PR TITLE
Certificate verification issue while enabling metrics and trace type of log data for AKS cluster

### LINKED ISSUE #1088: Certificate verification issue while enabling metrics and trace type of log data for AKS cluster
### Discussed in https://github.com/signalfx/splunk-otel-collector-chart/discussions/1087

<div type='discussions-op-text'>

<sup>Originally posted by **ajaykumarrc** December 18, 2023</sup>

i have installed splunk otel connector on AKS cluster version **1.25.15**  after enabling metric type logs am getting the below error any workaround for the below error.

`error   kubeletstatsreceiver@v0.91.0/scraper.go:77      call to /stats/summary endpoint failed  {"kind": "receiver", "name": "kubeletstats", "data_type": "metrics", "error": "Get \"https://1xx.2xx.xx.xxx:10250/stats/summary\": tls: failed to verify certificate: x509: cannot validate certificate for 1**.2***.**.**03 because it doesn't contain any IP SANs"}`

</div>

### PR DESCRIPTION
**Pull request by pratik141**
**Description:** <Describe what has changed.>
- Certificate verification issue fixed 

#1088

**Link to Splunk idea:** <Link to Splunk idea, see https://ideas.splunk.com>

**Testing:** <Describe what testing was performed and which tests were added.>

**Documentation:** <Describe the documentation added.>

### CODE REVIEW

**Comment by pratik141** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by jvoravong** [comment]
Hi @pratik141,

Could you please create an idea on [Splunk Ideas](https://ideas.splunk.com/) for this PR? Include these essential details:
- A detailed description of the issue this fix addresses.
- The Kubernetes distributions and versions impacted by this issue.
- If this fix specifically only needed to be applied to some or all supported Kubernetes distributions, we may need to consider implementing conditional logic to avoid affecting other distributions such as EKS or GKE.

Additionally, if an immediate deployment is necessary, you might consider using the `agent.config` helm value to apply this change. Thanks!

**Comment by jvoravong** [comment]
No recent activity on this PR, closing it.

**Comment by jvoravong** [comment]
Documentation was published related to this PR here: https://docs.splunk.com/observability/en/gdi/opentelemetry/collector-kubernetes/kubernetes-config-advanced.html#override-your-tls-configuration

**Pull request closed without merging**
