### PR TITLE
Release v0.58.0

### PR DESCRIPTION
**Pull request by foram-splunk**

### CODE REVIEW

**Comment by dmitryax** [comment]
The tests are failing. PTAL

**Comment by jvoravong** [comment]
Test failures are related to https://github.com/signalfx/splunk-otel-collector-chart/issues/519

**Comment by jvoravong** [comment]
Likely an upstream breaking change is causing this. DM'd Foram some possible leads.

**Comment by foram-splunk** [comment]
For some reason, `poll_interval` and `force_flush_period` are changed from string to map. The following config is working.
```yaml
filelog:
  poll_interval:
    duration: 200ms
  force_flush_period:
    duration: "0"
```

**Comment by jvoravong** [comment]
@foram-splunk good work finding a fix. It looks like an upstream change likely caused this issues (I suspect https://github.com/open-telemetry/opentelemetry-collector/pull/5839).

Before we merge this release, we should add a couple doc updates so users of this chart who have custom filelog receivers who use these configs have direction for how to address these issues when upgrading. Would you please add an entry to [UPGRADING.md](https://github.com/signalfx/splunk-otel-collector-chart/blob/main/UPGRADING.md) and include a an update for this breaking change in CHANGELOG.md ([example](https://github.com/signalfx/splunk-otel-collector-chart/blob/main/CHANGELOG.md#changed-12))

**Review by jvoravong — APPROVED** [review]

**Pull request merged**
