### PR TITLE
Enable ports based on telemetry type

### PR DESCRIPTION
**Pull request by jrcamp**

### CODE REVIEW

**Review by dmitryax — APPROVED** [review]
LGTM

**Comment by dmitryax** [comment]
I don't understand what's up with this changelog linter. let's merge for now

**Comment by dmitryax** [comment]
Oh you are merging into `otel-logs` branch. Why this change can't go straight into `main`?

**Comment by jrcamp** [comment]
> Oh you are merging into `otel-logs` branch. Why this change can't go straight into `main`?

Ah yeah main should be fine, rebased.

**Pull request merged**
