### PR TITLE
Add ServiceAccountName to secret-splunk-validation-hook pod

### LINKED ISSUE #780: Missing ServiceAccountName configuration for secret-splunk-validation-hook pod
### Describe the issue you're reporting

Hi, I believe we're missing the ``ServiceAccountName`` configuration for the  [secret-splunk-validation-hook pod](https://github.com/signalfx/splunk-otel-collector-chart/blob/main/helm-charts/splunk-otel-collector/templates/secret-splunk-validation-hook.yaml). Is there a reason it hasn't been added to the pod?

Since the  ``imagePullSecrets`` are [added to the ServiceAccount](https://github.com/signalfx/splunk-otel-collector-chart/blob/b36acaaa7b140170ea454ab905049c0f93e187cf/helm-charts/splunk-otel-collector/templates/serviceAccount.yaml#L3-L8), it would be helpful to use it on the hook pod when pulling the image from a private registry.

### PR DESCRIPTION
**Pull request by philipsabri**
Add ServiceAccountName to secret-splunk-validation-hook pod
Fixes #780

### CODE REVIEW

**Comment by philipsabri** [comment]
I was not sure if I was suppose to follow the [RELEASE.md](https://github.com/signalfx/splunk-otel-collector-chart/blob/main/RELEASE.md) instructions for this PR. I can update the PR it its suppose to be a part of this.

**Comment by jvoravong** [comment]
@philipsabri thanks for finding and contributing a fix for this. My team runs the release process about every 2 weeks, nothing has to be done by you. 
Can you please add an entry to the [CHANGELOG.md](https://github.com/signalfx/splunk-otel-collector-chart/blob/main/CHANGELOG.md) for this fix?

**Comment by philipsabri** [comment]
> @philipsabri thanks for finding and contributing a fix for this. My team runs the release process about every 2 weeks, nothing has to be done by you. Can you please add an entry to the [CHANGELOG.md](https://github.com/signalfx/splunk-otel-collector-chart/blob/main/CHANGELOG.md) for this fix?

Entry added to CHANGELOG.md

Thanks for quick response 👍

**Comment by philipsabri** [comment]
Updated with a fix 🤞 for the [changelog test](https://github.com/signalfx/splunk-otel-collector-chart/actions/runs/4927956199/jobs/8814974305)

**Review by jvoravong — APPROVED** [review]

**Pull request merged**
