### PR TITLE
Remove container runtime config

### PR DESCRIPTION
**Pull request by VihasMakwana**
- Remove `containerRuntime` setting. 
- Issue https://github.com/signalfx/splunk-otel-collector-chart/issues/829
- Create a common parser for crio/containerd

### CODE REVIEW

**Comment by VihasMakwana** [comment]
If anyone can take a look at this one

**Comment by jvoravong** [comment]
Please address the following so we can proceed with this PR:
- Splunk Platform Functional Tests: Ensure all tests pass.
- Validation Information: Given the potential for breaking changes in varying environments, it's essential to provide details about how the Acceptance Criteria (AC) validation.
  - Include a brief description of the testing methodology.
  - Please provide publicly accessible evidence/records of the tests conducted for the proposed changes on the [K8s distributions supported by Splunk](https://docs.splunk.com/Observability/gdi/opentelemetry/install-k8s.html#supported-kubernetes-distributions).
  - Specify the Kubernetes distributions (using containerd) and versions tested.

**Comment by jvoravong** [comment]
For testing coverage, https://github.com/signalfx/splunk-otel-collector-chart/pull/898 should help a lot.

**Comment by VihasMakwana** [comment]
WIP. Moving as draft till tested thoroughly.

**Pull request closed without merging**
